// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1
  AND business_id = (SELECT id FROM businesses WHERE slug = $2)
`

type DeleteBookmarkParams struct {
	UserID pgtype.UUID
	Slug   string
}

// Hapus lewat subquery slug supaya tetap bisa unbookmark profil yang sudah
// tidak published, dan menghapus yang tidak ada tetap sukses (idempotent).
func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.Exec(ctx, deleteBookmark, arg.UserID, arg.Slug)
	return err
}

const insertBookmark = `-- name: InsertBookmark :exec
INSERT INTO bookmarks (user_id, business_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertBookmarkParams struct {
	UserID     pgtype.UUID
	BusinessID pgtype.UUID
}

// Sudah ditandai sekalipun tetap dianggap sukses (idempotent).
func (q *Queries) InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error {
	_, err := q.db.Exec(ctx, insertBookmark, arg.UserID, arg.BusinessID)
	return err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT b.id, b.slug, b.owner_user_id, b.name, b.category, b.location, b.description, b.story, b.cover_image, b.cover_position, b.logo, b.founded_year, b.revenue_label, b.growth_label, b.revenue_series, b.seeking, b.seeking_objective, b.owner_name, b.owner_role, b.owner_bio, b.status, b.verified, b.created_at, b.updated_at
FROM bookmarks bm
JOIN businesses b ON b.id = bm.business_id
WHERE bm.user_id = $1
  AND b.status = 'published'
ORDER BY bm.created_at DESC, b.name ASC
`

type ListBookmarksParams struct {
	UserID pgtype.UUID
}

// Bookmarks hanya menampilkan profil published: draft pemilik sendiri tidak
// punya tempat di halaman bookmark publik mana pun.
func (q *Queries) ListBookmarks(ctx context.Context, arg ListBookmarksParams) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBookmarks, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerUserID,
			&i.Name,
			&i.Category,
			&i.Location,
			&i.Description,
			&i.Story,
			&i.CoverImage,
			&i.CoverPosition,
			&i.Logo,
			&i.FoundedYear,
			&i.RevenueLabel,
			&i.GrowthLabel,
			&i.RevenueSeries,
			&i.Seeking,
			&i.SeekingObjective,
			&i.OwnerName,
			&i.OwnerRole,
			&i.OwnerBio,
			&i.Status,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
