// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: businesses.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBusinessesByOwner = `-- name: CountBusinessesByOwner :one
SELECT count(*)
FROM businesses
WHERE owner_user_id = $1
  AND status <> 'archived'
`

type CountBusinessesByOwnerParams struct {
	OwnerUserID pgtype.UUID
}

func (q *Queries) CountBusinessesByOwner(ctx context.Context, arg CountBusinessesByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBusinessesByOwner, arg.OwnerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedBusinesses = `-- name: CountPublishedBusinesses :one
SELECT count(*)
FROM businesses b
WHERE b.status = 'published'
  AND ($1::text IS NULL OR b.category = $1)
  AND ($2::text IS NULL OR b.location ILIKE $2)
  AND (
        $3::text IS NULL
        OR b.name ILIKE '%' || $3 || '%'
        OR b.description ILIKE '%' || $3 || '%'
        OR b.category ILIKE '%' || $3 || '%'
        OR b.location ILIKE '%' || $3 || '%'
      )
`

type CountPublishedBusinessesParams struct {
	Category *string
	Location *string
	Q        *string
}

// Total rows matching the same filters, independent of LIMIT/OFFSET, so the
// list envelope's `total` stays correct even when the requested page is empty.
func (q *Queries) CountPublishedBusinesses(ctx context.Context, arg CountPublishedBusinessesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedBusinesses, arg.Category, arg.Location, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBmcEntriesByBusiness = `-- name: DeleteBmcEntriesByBusiness :exec
DELETE FROM bmc_entries WHERE business_id = $1
`

type DeleteBmcEntriesByBusinessParams struct {
	BusinessID pgtype.UUID
}

func (q *Queries) DeleteBmcEntriesByBusiness(ctx context.Context, arg DeleteBmcEntriesByBusinessParams) error {
	_, err := q.db.Exec(ctx, deleteBmcEntriesByBusiness, arg.BusinessID)
	return err
}

const deleteMilestonesByBusiness = `-- name: DeleteMilestonesByBusiness :exec
DELETE FROM business_milestones WHERE business_id = $1
`

type DeleteMilestonesByBusinessParams struct {
	BusinessID pgtype.UUID
}

// PATCH sends whole arrays, so replacing beats diffing positions one by one.
func (q *Queries) DeleteMilestonesByBusiness(ctx context.Context, arg DeleteMilestonesByBusinessParams) error {
	_, err := q.db.Exec(ctx, deleteMilestonesByBusiness, arg.BusinessID)
	return err
}

const existsBusinessBySlug = `-- name: ExistsBusinessBySlug :one
SELECT EXISTS (SELECT 1 FROM businesses WHERE slug = $1)
`

type ExistsBusinessBySlugParams struct {
	Slug string
}

func (q *Queries) ExistsBusinessBySlug(ctx context.Context, arg ExistsBusinessBySlugParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsBusinessBySlug, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, slug, owner_user_id, name, category, location, description, story, cover_image, cover_position, logo, founded_year, revenue_label, growth_label, revenue_series, seeking, seeking_objective, owner_name, owner_role, owner_bio, status, verified, created_at, updated_at
FROM businesses
WHERE id = $1
`

type GetBusinessByIDParams struct {
	ID pgtype.UUID
}

func (q *Queries) GetBusinessByID(ctx context.Context, arg GetBusinessByIDParams) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, arg.ID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Description,
		&i.Story,
		&i.CoverImage,
		&i.CoverPosition,
		&i.Logo,
		&i.FoundedYear,
		&i.RevenueLabel,
		&i.GrowthLabel,
		&i.RevenueSeries,
		&i.Seeking,
		&i.SeekingObjective,
		&i.OwnerName,
		&i.OwnerRole,
		&i.OwnerBio,
		&i.Status,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessesByIDs = `-- name: GetBusinessesByIDs :many
SELECT id, slug, owner_user_id, name, category, location, description, story, cover_image, cover_position, logo, founded_year, revenue_label, growth_label, revenue_series, seeking, seeking_objective, owner_name, owner_role, owner_bio, status, verified, created_at, updated_at
FROM businesses
WHERE id = ANY ($1::uuid[])
ORDER BY name ASC, id ASC
`

type GetBusinessesByIDsParams struct {
	Column1 []pgtype.UUID
}

func (q *Queries) GetBusinessesByIDs(ctx context.Context, arg GetBusinessesByIDsParams) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinessesByIDs, arg.Column1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerUserID,
			&i.Name,
			&i.Category,
			&i.Location,
			&i.Description,
			&i.Story,
			&i.CoverImage,
			&i.CoverPosition,
			&i.Logo,
			&i.FoundedYear,
			&i.RevenueLabel,
			&i.GrowthLabel,
			&i.RevenueSeries,
			&i.Seeking,
			&i.SeekingObjective,
			&i.OwnerName,
			&i.OwnerRole,
			&i.OwnerBio,
			&i.Status,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedBusinessBySlug = `-- name: GetPublishedBusinessBySlug :one
SELECT id, slug, owner_user_id, name, category, location, description, story, cover_image, cover_position, logo, founded_year, revenue_label, growth_label, revenue_series, seeking, seeking_objective, owner_name, owner_role, owner_bio, status, verified, created_at, updated_at
FROM businesses
WHERE slug = $1
  AND status = 'published'
`

type GetPublishedBusinessBySlugParams struct {
	Slug string
}

func (q *Queries) GetPublishedBusinessBySlug(ctx context.Context, arg GetPublishedBusinessBySlugParams) (Business, error) {
	row := q.db.QueryRow(ctx, getPublishedBusinessBySlug, arg.Slug)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Description,
		&i.Story,
		&i.CoverImage,
		&i.CoverPosition,
		&i.Logo,
		&i.FoundedYear,
		&i.RevenueLabel,
		&i.GrowthLabel,
		&i.RevenueSeries,
		&i.Seeking,
		&i.SeekingObjective,
		&i.OwnerName,
		&i.OwnerRole,
		&i.OwnerBio,
		&i.Status,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBmcEntry = `-- name: InsertBmcEntry :exec
INSERT INTO bmc_entries (business_id, label, value, position)
VALUES ($1, $2, $3, $4)
`

type InsertBmcEntryParams struct {
	BusinessID pgtype.UUID
	Label      string
	Value      string
	Position   int32
}

func (q *Queries) InsertBmcEntry(ctx context.Context, arg InsertBmcEntryParams) error {
	_, err := q.db.Exec(ctx, insertBmcEntry,
		arg.BusinessID,
		arg.Label,
		arg.Value,
		arg.Position,
	)
	return err
}

const insertBusiness = `-- name: InsertBusiness :one
INSERT INTO businesses (
    slug, owner_user_id, name, category, location, description, story,
    cover_image, cover_position, logo, founded_year,
    revenue_label, growth_label, revenue_series, seeking, seeking_objective,
    owner_name, owner_role, owner_bio, status, verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21
)
RETURNING id, slug, owner_user_id, name, category, location, description, story, cover_image, cover_position, logo, founded_year, revenue_label, growth_label, revenue_series, seeking, seeking_objective, owner_name, owner_role, owner_bio, status, verified, created_at, updated_at
`

type InsertBusinessParams struct {
	Slug             string
	OwnerUserID      pgtype.UUID
	Name             string
	Category         string
	Location         string
	Description      string
	Story            string
	CoverImage       *string
	CoverPosition    *string
	Logo             *string
	FoundedYear      int32
	RevenueLabel     *string
	GrowthLabel      *string
	RevenueSeries    []float64
	Seeking          []string
	SeekingObjective *string
	OwnerName        string
	OwnerRole        string
	OwnerBio         string
	Status           string
	Verified         bool
}

func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, insertBusiness,
		arg.Slug,
		arg.OwnerUserID,
		arg.Name,
		arg.Category,
		arg.Location,
		arg.Description,
		arg.Story,
		arg.CoverImage,
		arg.CoverPosition,
		arg.Logo,
		arg.FoundedYear,
		arg.RevenueLabel,
		arg.GrowthLabel,
		arg.RevenueSeries,
		arg.Seeking,
		arg.SeekingObjective,
		arg.OwnerName,
		arg.OwnerRole,
		arg.OwnerBio,
		arg.Status,
		arg.Verified,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Description,
		&i.Story,
		&i.CoverImage,
		&i.CoverPosition,
		&i.Logo,
		&i.FoundedYear,
		&i.RevenueLabel,
		&i.GrowthLabel,
		&i.RevenueSeries,
		&i.Seeking,
		&i.SeekingObjective,
		&i.OwnerName,
		&i.OwnerRole,
		&i.OwnerBio,
		&i.Status,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMilestone = `-- name: InsertMilestone :exec
INSERT INTO business_milestones (business_id, year, title, description, position)
VALUES ($1, $2, $3, $4, $5)
`

type InsertMilestoneParams struct {
	BusinessID  pgtype.UUID
	Year        int32
	Title       string
	Description *string
	Position    int32
}

func (q *Queries) InsertMilestone(ctx context.Context, arg InsertMilestoneParams) error {
	_, err := q.db.Exec(ctx, insertMilestone,
		arg.BusinessID,
		arg.Year,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	return err
}

const listBmcEntriesByBusinessIDs = `-- name: ListBmcEntriesByBusinessIDs :many
SELECT id, business_id, label, value, position
FROM bmc_entries
WHERE business_id = ANY ($1::uuid[])
ORDER BY business_id, position
`

type ListBmcEntriesByBusinessIDsParams struct {
	Column1 []pgtype.UUID
}

func (q *Queries) ListBmcEntriesByBusinessIDs(ctx context.Context, arg ListBmcEntriesByBusinessIDsParams) ([]BmcEntry, error) {
	rows, err := q.db.Query(ctx, listBmcEntriesByBusinessIDs, arg.Column1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BmcEntry{}
	for rows.Next() {
		var i BmcEntry
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Label,
			&i.Value,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessesByOwner = `-- name: ListBusinessesByOwner :many
SELECT id, slug, owner_user_id, name, category, location, description, story, cover_image, cover_position, logo, founded_year, revenue_label, growth_label, revenue_series, seeking, seeking_objective, owner_name, owner_role, owner_bio, status, verified, created_at, updated_at
FROM businesses
WHERE owner_user_id = $1
  AND status <> 'archived'
ORDER BY created_at DESC, id ASC
LIMIT $2 OFFSET $3
`

type ListBusinessesByOwnerParams struct {
	OwnerUserID pgtype.UUID
	Limit       int32
	Offset      int32
}

// Owner dashboard list: every profile owned by one account, drafts included,
// newest first. The public list only ever shows published rows; this is the
// query the owner's own dashboard reads. Archived profiles are left out: the
// owner deleted them, so they must not reappear on the dashboard.
func (q *Queries) ListBusinessesByOwner(ctx context.Context, arg ListBusinessesByOwnerParams) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinessesByOwner, arg.OwnerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerUserID,
			&i.Name,
			&i.Category,
			&i.Location,
			&i.Description,
			&i.Story,
			&i.CoverImage,
			&i.CoverPosition,
			&i.Logo,
			&i.FoundedYear,
			&i.RevenueLabel,
			&i.GrowthLabel,
			&i.RevenueSeries,
			&i.Seeking,
			&i.SeekingObjective,
			&i.OwnerName,
			&i.OwnerRole,
			&i.OwnerBio,
			&i.Status,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestonesByBusinessIDs = `-- name: ListMilestonesByBusinessIDs :many
SELECT id, business_id, year, title, description, position
FROM business_milestones
WHERE business_id = ANY ($1::uuid[])
ORDER BY business_id, position, year
`

type ListMilestonesByBusinessIDsParams struct {
	Column1 []pgtype.UUID
}

// One round-trip for the whole list: rows are grouped by business_id in the
// service layer instead of querying per card.
func (q *Queries) ListMilestonesByBusinessIDs(ctx context.Context, arg ListMilestonesByBusinessIDsParams) ([]BusinessMilestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByBusinessIDs, arg.Column1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessMilestone{}
	for rows.Next() {
		var i BusinessMilestone
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Year,
			&i.Title,
			&i.Description,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBusinessIDs = `-- name: ListPublishedBusinessIDs :many
SELECT b.id
FROM businesses b
WHERE b.status = 'published'
  AND ($1::text IS NULL OR b.category = $1)
  AND ($2::text IS NULL OR b.location ILIKE $2)
  AND (
        $3::text IS NULL
        OR b.name ILIKE '%' || $3 || '%'
        OR b.description ILIKE '%' || $3 || '%'
        OR b.category ILIKE '%' || $3 || '%'
        OR b.location ILIKE '%' || $3 || '%'
      )
ORDER BY b.name ASC, b.id ASC
LIMIT $5 OFFSET $4
`

type ListPublishedBusinessIDsParams struct {
	Category *string
	Location *string
	Q        *string
	Offset   int32
	Limit    int32
}

// Public list: page through matching published profiles by id only. Rows are
// loaded by GetBusinessesByIDs afterwards so list and detail share a single
// row->domain mapper. The match total is a separate query
// (CountPublishedBusinesses) because a count(*) OVER () window only exists on
// returned rows, so it reads 0 on a page past the last row.
// The id tiebreaker keeps paging deterministic when two profiles share a name.
func (q *Queries) ListPublishedBusinessIDs(ctx context.Context, arg ListPublishedBusinessIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPublishedBusinessIDs,
		arg.Category,
		arg.Location,
		arg.Q,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses
SET name              = $2,
    category          = $3,
    location          = $4,
    description       = $5,
    story             = $6,
    cover_image       = $7,
    cover_position    = $8,
    logo              = $9,
    founded_year      = $10,
    revenue_label     = $11,
    growth_label      = $12,
    revenue_series    = $13,
    seeking           = $14,
    seeking_objective = $15,
    owner_name        = $16,
    owner_role        = $17,
    owner_bio         = $18,
    status            = $19,
    verified          = $20,
    updated_at        = now()
WHERE id = $1
RETURNING id, slug, owner_user_id, name, category, location, description, story, cover_image, cover_position, logo, founded_year, revenue_label, growth_label, revenue_series, seeking, seeking_objective, owner_name, owner_role, owner_bio, status, verified, created_at, updated_at
`

type UpdateBusinessParams struct {
	ID               pgtype.UUID
	Name             string
	Category         string
	Location         string
	Description      string
	Story            string
	CoverImage       *string
	CoverPosition    *string
	Logo             *string
	FoundedYear      int32
	RevenueLabel     *string
	GrowthLabel      *string
	RevenueSeries    []float64
	Seeking          []string
	SeekingObjective *string
	OwnerName        string
	OwnerRole        string
	OwnerBio         string
	Status           string
	Verified         bool
}

// Full-row update: the service reads the row, merges the fields the client
// sent, and writes everything back, one query instead of a SET per field.
// slug and owner_user_id are absent on purpose: a profile URL never changes
// and ownership never transfers through PATCH.
func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusiness,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Location,
		arg.Description,
		arg.Story,
		arg.CoverImage,
		arg.CoverPosition,
		arg.Logo,
		arg.FoundedYear,
		arg.RevenueLabel,
		arg.GrowthLabel,
		arg.RevenueSeries,
		arg.Seeking,
		arg.SeekingObjective,
		arg.OwnerName,
		arg.OwnerRole,
		arg.OwnerBio,
		arg.Status,
		arg.Verified,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Description,
		&i.Story,
		&i.CoverImage,
		&i.CoverPosition,
		&i.Logo,
		&i.FoundedYear,
		&i.RevenueLabel,
		&i.GrowthLabel,
		&i.RevenueSeries,
		&i.Seeking,
		&i.SeekingObjective,
		&i.OwnerName,
		&i.OwnerRole,
		&i.OwnerBio,
		&i.Status,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
