// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :exec
UPDATE email_verification_tokens
SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL
`

type ConsumeEmailVerificationTokenParams struct {
	TokenHash string
}

func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, arg ConsumeEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, consumeEmailVerificationToken, arg.TokenHash)
	return err
}

const deleteEmailVerificationTokensByUser = `-- name: DeleteEmailVerificationTokensByUser :exec
DELETE FROM email_verification_tokens
WHERE user_id = $1
`

type DeleteEmailVerificationTokensByUserParams struct {
	UserID pgtype.UUID
}

func (q *Queries) DeleteEmailVerificationTokensByUser(ctx context.Context, arg DeleteEmailVerificationTokensByUserParams) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensByUser, arg.UserID)
	return err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :exec
DELETE FROM email_verification_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailVerificationTokens)
	return err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT token_hash, user_id, created_at, expires_at, used_at
FROM email_verification_tokens
WHERE token_hash = $1
`

type GetEmailVerificationTokenParams struct {
	TokenHash string
}

func (q *Queries) GetEmailVerificationToken(ctx context.Context, arg GetEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationToken, arg.TokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
INSERT INTO email_verification_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type InsertEmailVerificationTokenParams struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerificationToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users
SET email_verified_at = now()
WHERE id = $1 AND email_verified_at IS NULL
`

type SetUserEmailVerifiedParams struct {
	ID pgtype.UUID
}

// SetUserEmailVerified is idempotent: the guard keeps the first verification
// time instead of overwriting it on a repeat call.
func (q *Queries) SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, arg.ID)
	return err
}
