// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BmcEntry struct {
	ID         pgtype.UUID
	BusinessID pgtype.UUID
	Label      string
	Value      string
	Position   int32
}

type Bookmark struct {
	UserID     pgtype.UUID
	BusinessID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type Business struct {
	ID               pgtype.UUID
	Slug             string
	OwnerUserID      pgtype.UUID
	Name             string
	Category         string
	Location         string
	Description      string
	Story            string
	CoverImage       *string
	CoverPosition    *string
	Logo             *string
	FoundedYear      int32
	RevenueLabel     *string
	GrowthLabel      *string
	RevenueSeries    []float64
	Seeking          []string
	SeekingObjective *string
	OwnerName        string
	OwnerRole        string
	OwnerBio         string
	Status           string
	Verified         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type BusinessMilestone struct {
	ID          pgtype.UUID
	BusinessID  pgtype.UUID
	Year        int32
	Title       string
	Description *string
	Position    int32
}

type EmailVerificationToken struct {
	TokenHash string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Session struct {
	Token     string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Name            string
	Email           string
	PasswordHash    string
	Role            string
	CreatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}
