// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions
WHERE user_id = $1
  AND token <> $2
`

type DeleteOtherSessionsParams struct {
	UserID pgtype.UUID
	Token  string
}

// Changing a password logs out every other device but keeps the caller signed
// in, so the request that changed it does not invalidate its own cookie.
func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.Token)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions
WHERE token = $1
`

type DeleteSessionByTokenParams struct {
	Token string
}

func (q *Queries) DeleteSessionByToken(ctx context.Context, arg DeleteSessionByTokenParams) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, arg.Token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT token, user_id, expires_at
FROM sessions
WHERE token = $1
`

type GetSessionByTokenParams struct {
	Token string
}

type GetSessionByTokenRow struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, arg.Token)
	var i GetSessionByTokenRow
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type InsertSessionParams struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}
